# Generated by Django 5.2.4 on 2025-07-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('자유', '자유'), ('둥지', '둥지'), ('공지', '공지')], default='자유', max_length=10),
        ),
    ]
