# Generated by Django 5.2.4 on 2025-07-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
